/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vehicle.vehicleinfo;


import Connection.C_onnection;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

import javax.swing.JOptionPane;

import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;
import vehicle.loginui.process;

/**
 *
 * @author user
 */
public class company extends javax.swing.JFrame {
     public String s;
  byte[] myimage;

    /**
     * Creates new form orders
     */
    public company() {
        initComponents();
        Update();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        phone = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        companytable = new javax.swing.JTable();
        PHONE = new javax.swing.JTextField();
        address = new javax.swing.JTextField();
        compid = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        cname = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        save = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        update = new javax.swing.JButton();
        website = new javax.swing.JTextField();
        signupclear = new javax.swing.JButton();
        back = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        phone.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        companytable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "NAME", "PHONE", "EMAIL", "ADDRESS"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        companytable.setRowHeight(25);
        companytable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                companytableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(companytable);

        phone.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 1220, 265));

        PHONE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PHONEActionPerformed(evt);
            }
        });
        phone.add(PHONE, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 470, 161, 28));
        phone.add(address, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 410, 161, 29));

        compid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                compidActionPerformed(evt);
            }
        });
        phone.add(compid, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 420, 161, 29));
        phone.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 370, 161, 29));

        cname.setFont(new java.awt.Font("Segoe Print", 0, 11)); // NOI18N
        cname.setText("NAME");
        phone.add(cname, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 380, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe Print", 0, 11)); // NOI18N
        jLabel2.setText("PHONE");
        phone.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 470, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe Print", 0, 11)); // NOI18N
        jLabel3.setText("EMAIL");
        phone.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 370, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe Print", 0, 11)); // NOI18N
        jLabel5.setText("ADDRESS");
        phone.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 420, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe Print", 0, 11)); // NOI18N
        jLabel7.setText("COMPID");
        phone.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 430, -1, -1));

        save.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        save.setText("SAVE");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        phone.add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 370, 110, -1));

        delete.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        delete.setText("DELETE");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        phone.add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 370, 110, -1));

        update.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        update.setText("UPDATE");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        phone.add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 370, 110, -1));
        phone.add(website, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 370, 161, 29));

        signupclear.setBackground(new java.awt.Color(204, 204, 204));
        signupclear.setFont(new java.awt.Font("Segoe Print", 1, 15)); // NOI18N
        signupclear.setText("CLEAR");
        signupclear.setBorder(null);
        signupclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupclearActionPerformed(evt);
            }
        });
        phone.add(signupclear, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 370, 110, 30));

        back.setBackground(new java.awt.Color(255, 102, 51));
        back.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        back.setForeground(new java.awt.Color(255, 255, 255));
        back.setText("BACK");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        phone.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 460, 110, 30));

        jPanel1.setBackground(new java.awt.Color(255, 102, 51));

        jLabel1.setFont(new java.awt.Font("Segoe Print", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("COMPANY DETAILES");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(525, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(504, 504, 504))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        phone.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 1290, 50));

        getContentPane().add(phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1281, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        C_onnection connect=new C_onnection();
        PreparedStatement ps;
        ResultSet rs;
        try{

                
         int i = companytable.getSelectedRow();

            TableModel model = companytable.getModel();
          
           
            
            
        String query = "UPDATE company SET compid=?,compname=?,phone=?,email=?,address=? WHERE compid =?;";

        ps=connect.getConnection().prepareStatement(query);

        
        ps.setString(1,compid.getText());
         ps.setString(2,name.getText());
        ps.setString(3,PHONE.getText());
       
        ps.setString(4,website.getText());
         ps.setString(5,address.getText());
        ps.setString(6,model.getValueAt(i,0).toString());
        
        ps.executeUpdate();
            Update();
        JOptionPane.showMessageDialog(null,"updated", "successfull", JOptionPane.INFORMATION_MESSAGE);
         name.setText(null);
        compid.setText(null);
        PHONE.setText(null);
        address.setText(null);
        website.setText(null);
       
       
        }
        catch(Exception e){
            System.out.println("ERROR:"+e.getMessage());
        }
    }//GEN-LAST:event_updateActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        try{

            C_onnection connect=new C_onnection();
            PreparedStatement ps;
            ResultSet rs;
            int i = companytable.getSelectedRow();

            TableModel model = companytable.getModel();
            String str=model.getValueAt(i,0).toString();
            System.out.println(str);
            String query="DELETE FROM company WHERE compid=?";
            ps=connect.getConnection().prepareStatement(query);
            ps.setString(1,model.getValueAt(i,0).toString());
            ps.executeUpdate();
            Update();
        }
        catch(Exception e){

        }
    }//GEN-LAST:event_deleteActionPerformed

    // to insert the customers
    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        try{
            C_onnection connect=new C_onnection();

            PreparedStatement ps;
            ps = connect.getConnection().prepareStatement("INSERT INTO company VALUES(?,?,?,?,?);");

            //InputStream is=new FileInputStream(new File(s));
            ps.setString(1, compid.getText());
            ps.setString(2,name.getText());
            
            ps.setString(3, PHONE.getText());
            ps.setString(4, website.getText());
            ps.setString(5, address.getText());

            
           
            ps.executeUpdate();
            Update();
            JOptionPane.showMessageDialog(null,"data inserted");
             name.setText(null);
        compid.setText(null);
        PHONE.setText(null);
        address.setText(null);
        website.setText(null);

        }
        catch(Exception e){
            System.out.println("ERROR:   "+e.getMessage());

        }
    }//GEN-LAST:event_saveActionPerformed

    private void compidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_compidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_compidActionPerformed

    private void PHONEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PHONEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PHONEActionPerformed

    private void signupclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupclearActionPerformed
       name.setText(null);
        compid.setText(null);
        PHONE.setText(null);
        address.setText(null);
        website.setText(null);

    }//GEN-LAST:event_signupclearActionPerformed

    private void companytableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_companytableMouseClicked
       C_onnection connect=new C_onnection();
        PreparedStatement ps;
        ResultSet rs;
        
        try{
            
           
         int i = companytable.getSelectedRow();

            TableModel model = companytable.getModel();
            String str=model.getValueAt(i,0).toString();
            ps=connect.getConnection().prepareStatement("SELECT * FROM company  WHERE compid=? ;");
            
             ps.setString(1,model.getValueAt(i,0).toString());
             
            rs=ps.executeQuery();
            while(rs.next()){
             compid.setText(rs.getString("compid"));

       name.setText(rs.getString("compname"));

        PHONE.setText(rs.getString("phone"));

        website.setText(rs.getString("email"));
        address.setText(rs.getString("address"));
            }   
            
            
        }
        catch(SQLException e){
            System.out.println("ERROR:"+e.getMessage());
        }      
    }//GEN-LAST:event_companytableMouseClicked

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        this.setVisible(false);
         new process().setVisible(true);
    }//GEN-LAST:event_backActionPerformed

    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(company.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(company.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(company.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(company.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new company().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField PHONE;
    private javax.swing.JTextField address;
    private javax.swing.JButton back;
    private javax.swing.JLabel cname;
    private javax.swing.JTable companytable;
    private javax.swing.JTextField compid;
    private javax.swing.JButton delete;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField name;
    private javax.swing.JPanel phone;
    private javax.swing.JButton save;
    private javax.swing.JButton signupclear;
    private javax.swing.JButton update;
    private javax.swing.JTextField website;
    // End of variables declaration//GEN-END:variables
  private void Update() {
        C_onnection connect=new C_onnection();
        PreparedStatement ps;
        ResultSet rs;
        
        try{
            ps=connect.getConnection().prepareStatement("SELECT compid,compname,phone,email,address FROM company ;");
            rs=ps.executeQuery();
            companytable.setModel(DbUtils.resultSetToTableModel(rs));
            
        }
        catch(SQLException e){
            System.out.println("ERROR:"+e.getMessage());
        }

  }
   

}
