/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vehicle.loginui;

import Connection.C_onnection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import vehicle.vehicleinfo.userlogin;

/**
 *
 * @author user
 */
public class Signup extends javax.swing.JFrame {

    /**
     * Creates new form Signup
     */
    public Signup() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton4 = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        signupfname = new javax.swing.JTextField();
        signuplname = new javax.swing.JTextField();
        signupusername = new javax.swing.JTextField();
        signuppassword = new javax.swing.JTextField();
        confirm = new javax.swing.JTextField();
        signupclear = new javax.swing.JButton();
        signupsave = new javax.swing.JButton();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();

        jButton4.setText("jButton4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setFocusable(false);
        jPanel1.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 102, 0));

        jLabel1.setBackground(new java.awt.Color(255, 51, 0));
        jLabel1.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Sign Up");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 400, 52);

        signupfname.setBackground(new java.awt.Color(51, 51, 51));
        signupfname.setFont(new java.awt.Font("Calibri", 0, 15)); // NOI18N
        signupfname.setForeground(new java.awt.Color(255, 255, 255));
        signupfname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        signupfname.setCaretColor(new java.awt.Color(255, 255, 255));
        jPanel1.add(signupfname);
        signupfname.setBounds(100, 100, 210, 30);

        signuplname.setBackground(new java.awt.Color(51, 51, 51));
        signuplname.setFont(new java.awt.Font("Calibri", 0, 15)); // NOI18N
        signuplname.setForeground(new java.awt.Color(255, 255, 255));
        signuplname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        signuplname.setCaretColor(new java.awt.Color(255, 255, 255));
        jPanel1.add(signuplname);
        signuplname.setBounds(100, 170, 210, 30);

        signupusername.setBackground(new java.awt.Color(51, 51, 51));
        signupusername.setFont(new java.awt.Font("Calibri", 0, 15)); // NOI18N
        signupusername.setForeground(new java.awt.Color(255, 255, 255));
        signupusername.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        signupusername.setCaretColor(new java.awt.Color(255, 255, 255));
        jPanel1.add(signupusername);
        signupusername.setBounds(100, 240, 210, 30);

        signuppassword.setBackground(new java.awt.Color(51, 51, 51));
        signuppassword.setFont(new java.awt.Font("Calibri", 0, 15)); // NOI18N
        signuppassword.setForeground(new java.awt.Color(255, 255, 255));
        signuppassword.setBorder(null);
        signuppassword.setCaretColor(new java.awt.Color(255, 255, 255));
        jPanel1.add(signuppassword);
        signuppassword.setBounds(100, 310, 210, 30);

        confirm.setBackground(new java.awt.Color(51, 51, 51));
        confirm.setFont(new java.awt.Font("Calibri", 0, 15)); // NOI18N
        confirm.setForeground(new java.awt.Color(255, 255, 255));
        confirm.setBorder(null);
        confirm.setCaretColor(new java.awt.Color(255, 255, 255));
        jPanel1.add(confirm);
        confirm.setBounds(100, 380, 210, 30);

        signupclear.setBackground(new java.awt.Color(255, 51, 0));
        signupclear.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        signupclear.setForeground(new java.awt.Color(255, 255, 255));
        signupclear.setText("CLEAR");
        signupclear.setBorder(null);
        signupclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupclearActionPerformed(evt);
            }
        });
        jPanel1.add(signupclear);
        signupclear.setBounds(100, 460, 80, 30);

        signupsave.setBackground(new java.awt.Color(255, 51, 0));
        signupsave.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        signupsave.setForeground(new java.awt.Color(255, 255, 255));
        signupsave.setText("SAVE");
        signupsave.setBorder(null);
        signupsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupsaveActionPerformed(evt);
            }
        });
        jPanel1.add(signupsave);
        signupsave.setBounds(230, 460, 80, 30);

        jTextField6.setEditable(false);
        jTextField6.setBackground(new java.awt.Color(51, 51, 51));
        jTextField6.setFont(new java.awt.Font("Calibri", 0, 15)); // NOI18N
        jTextField6.setForeground(new java.awt.Color(255, 255, 255));
        jTextField6.setText("FIRST NAME :");
        jTextField6.setBorder(null);
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField6);
        jTextField6.setBounds(100, 80, 80, 19);

        jTextField7.setEditable(false);
        jTextField7.setBackground(new java.awt.Color(51, 51, 51));
        jTextField7.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jTextField7.setForeground(new java.awt.Color(255, 255, 255));
        jTextField7.setText("LAST NAME :");
        jTextField7.setBorder(null);
        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField7);
        jTextField7.setBounds(100, 150, 73, 17);

        jTextField8.setEditable(false);
        jTextField8.setBackground(new java.awt.Color(51, 51, 51));
        jTextField8.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jTextField8.setForeground(new java.awt.Color(255, 255, 255));
        jTextField8.setText("USER NAME :");
        jTextField8.setBorder(null);
        jPanel1.add(jTextField8);
        jTextField8.setBounds(100, 220, 80, 17);

        jTextField9.setEditable(false);
        jTextField9.setBackground(new java.awt.Color(51, 51, 51));
        jTextField9.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jTextField9.setForeground(new java.awt.Color(255, 255, 255));
        jTextField9.setText("PASSWORD :");
        jTextField9.setBorder(null);
        jPanel1.add(jTextField9);
        jTextField9.setBounds(100, 290, 80, 17);

        jTextField10.setEditable(false);
        jTextField10.setBackground(new java.awt.Color(51, 51, 51));
        jTextField10.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jTextField10.setForeground(new java.awt.Color(255, 255, 255));
        jTextField10.setText("CONFIRM PASSWORD :");
        jTextField10.setBorder(null);
        jPanel1.add(jTextField10);
        jTextField10.setBounds(100, 360, 140, 17);

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(100, 130, 210, 10);

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator2);
        jSeparator2.setBounds(100, 200, 210, 10);

        jSeparator3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator3);
        jSeparator3.setBounds(100, 270, 210, 30);

        jSeparator4.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator4);
        jSeparator4.setBounds(100, 340, 210, 20);

        jSeparator5.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator5);
        jSeparator5.setBounds(100, 410, 210, 20);

        jButton1.setText("<-");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(330, 60, 60, 23);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 398, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 518, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(414, 557));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void signupsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupsaveActionPerformed
        C_onnection connect=new C_onnection();
        PreparedStatement ps;
        ResultSet rs;
        try{
            int i=0;
          String x=signuppassword.getText();
          String y=confirm.getText();
            
            if(x.equals(y)){
            
            
            
        String query2="INSERT INTO users VALUES(?,?,?,?,0);";
        ps=connect.getConnection().prepareStatement(query2);
        ps.setString(1,signupfname.getText());
                 ps.setString(2,signuplname.getText());
                 
                 
                          ps.setString(3,signupusername.getText());
                                   ps.setString(4,signuppassword.getText());
                                   
                                           
                                            
          ps.executeUpdate();
           JOptionPane.showMessageDialog(null,"insertion", "successfull", JOptionPane.INFORMATION_MESSAGE);
             
            }
            
            else{
             JOptionPane.showMessageDialog(null,"check the password", "successfull", JOptionPane.INFORMATION_MESSAGE);
            }
                }
        catch(Exception e){
            System.out.println("ERROR:"+e.getMessage());
        }
    }//GEN-LAST:event_signupsaveActionPerformed

    private void signupclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupclearActionPerformed
        signupfname.setText(null);
         signuplname.setText(null);
         signupusername.setText(null);
         signuppassword.setText(null);
         confirm.setText(null);
        
        
        
    }//GEN-LAST:event_signupclearActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       setVisible(false);
       
       new adminoruser().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField confirm;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JButton signupclear;
    private javax.swing.JTextField signupfname;
    private javax.swing.JTextField signuplname;
    private javax.swing.JTextField signuppassword;
    private javax.swing.JButton signupsave;
    private javax.swing.JTextField signupusername;
    // End of variables declaration//GEN-END:variables
}
